server:
  port: 8081
redisson:
  timeout: 3000
  address: redis://112.124.27.136:6379
  password: sangsang
  database: 1
  connectionPoolSize: 64
  sentinelAddresses: redis://112.124.27.136:6377,redis://112.124.27.136:6378,redis://112.124.27.136:6379
  masterName: mymaster
  connectionMinimumIdleSize: 10
  slaveConnectionPoolSize: 250
  masterConnectionPoolSize: 250